# 端口号
server:
  port: 8002
spring:
  application:
    name: demo-consume
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:8988/
    sender:
      type: web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka