server:
  port: 8001 # 端口
  servlet:
    encoding:
      charset: UTF-8 # 编码 解决返回乱码
      force: true
      enabled: true
# 应用名
spring:
  application:
    name: demo-core
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:8988/
    sender:
      type: web


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka