server:
  port: 8000 # 端口
  servlet:
    encoding:
      charset: UTF-8 # 编码 解决返回乱码
      force: true
      enabled: true
# 应用名
spring:
  application:
    name: demo-getway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
# 网关配置, 网关IP:网关端口/v1/**  >>> 微服务:端口/**
zuul:
  routes:
    demo-core: /v1/**
  debug:
    request: true  #如果设置了这个，默认所有的请求都会debug
    include-debug-header: true
logging:
  level:
    com.netflix: DEBUG